volumes:
  ecomoda:
    external: true
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ecomoda:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
  fastapi:
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: mongodb://admin:password@mongo:27017
      CORS_HOST: http://localhost:3000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
